apiVersion: apps/v1
kind: Deployment
metadata:
  name: zainab-ara-deploy
  labels:
    app: zainab-ara-deploy-lbl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zainab-ara-app
  template:
    metadata:
      labels:
        app: zainab-ara-app
    spec:
      containers:
      - name: zainab-ara-container
        image: zainabara/zainab-ara-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zainab-ara-np-service
  labels:
    app: zainab-ara-app
spec:
  selector:
    app: zainab-ara-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 30001
    port: 8080
    targetPort: 8080
